export const BRAND = {
  name: "SMART WORLD ORDER",
  shortName: "SWO",
  tagline: "Both eyes on what's really going on",
  mission: "Realities and Facts at your doorstep",
  vision: "A Global Family Platform",
  founder: "Dr M Irfan Qadir Thaheem",
  values: ["Unity", "Integrity", "Universality"],
  email: "dr.mirfan5577@gmail.com",
  whatsapp: "03004737757",
  slogan:
    "Neither a Global Village nor a Global Community — It's a Global Family Platform",
};

export const CHANNELS = [
  {
    id: "uniorbi",
    name: "UniOrbi",
    handle: "@UniOrbi",
    platform: "YouTube",
    color: "#FF0000",
    colorClass: "from-red-600 to-red-900",
    borderClass: "border-red-500/30",
    glowClass: "hover:shadow-red-500/20",
    icon: "📺",
    description:
      "SMART WORLD ORDER's main broadcast channel. Dark realities, hidden facts, and deeper global insights.",
    categories: [
      "Motivational",
      "Political",
      "Educational",
      "Social",
      "International",
    ],
    url: "https://youtube.com/@UniOrbi",
    badge: "MAIN CHANNEL",
  },
  {
    id: "uniedge",
    name: "UniEdge",
    handle: "@UniEdge",
    platform: "YouTube / Digital",
    color: "#0EA5E9",
    colorClass: "from-sky-500 to-blue-900",
    borderClass: "border-sky-500/30",
    glowClass: "hover:shadow-sky-500/20",
    icon: "⚡",
    description:
      "Next-generation digital media platform. 4K content, Creator Studio, Global Community — No Censorship, Real Freedom.",
    categories: [
      "4K Content",
      "Creator Studio",
      "Global Community",
      "No Censorship",
    ],
    url: "https://youtube.com/@UniEdge",
    badge: "COMING SOON",
  },
  {
    id: "uninews",
    name: "UniNews",
    handle: "@UniNews",
    platform: "News",
    color: "#10B981",
    colorClass: "from-emerald-500 to-green-900",
    borderClass: "border-emerald-500/30",
    glowClass: "hover:shadow-emerald-500/20",
    icon: "📰",
    description:
      "Breaking news and analysis from a truth-first perspective. No bias, no filters.",
    categories: ["Breaking News", "Analysis", "Hidden Facts", "Reality Checks"],
    url: "#",
    badge: "COMING SOON",
  },
  {
    id: "unifeel",
    name: "UniFeel",
    handle: "@UniFeel",
    platform: "Social App",
    color: "#8B5CF6",
    colorClass: "from-violet-500 to-purple-900",
    borderClass: "border-violet-500/30",
    glowClass: "hover:shadow-violet-500/20",
    icon: "💫",
    description:
      "The social platform for the Global Family. Connect, share, and unite across all borders.",
    categories: ["Social Network", "Global Family", "Unity", "Community"],
    url: "#",
    badge: "COMING SOON",
  },
  {
    id: "unispark",
    name: "UniSpark",
    handle: "@UniSpark",
    platform: "Poetry / Arts",
    color: "#F59E0B",
    colorClass: "from-amber-500 to-orange-900",
    borderClass: "border-amber-500/30",
    glowClass: "hover:shadow-amber-500/20",
    icon: "✨",
    description:
      "The poetry, arts, and inspirational content channel of the SWO ecosystem.",
    categories: ["Poetry", "Arts", "Motivation", "Inspiration"],
    url: "#",
    badge: "COMING SOON",
  },
];

export const SOCIAL_PLATFORMS = [
  {
    name: "YouTube",
    handle: "@UniOrbi",
    url: "https://youtube.com/@UniOrbi",
    color: "#FF0000",
    bgClass: "bg-red-600",
    hoverClass: "hover:bg-red-500",
    description: "Subscribe for video content",
    icon: "YT",
  },
  {
    name: "Instagram",
    handle: "@smartworldorder",
    url: "https://instagram.com/smartworldorder",
    color: "#E1306C",
    bgClass: "bg-gradient-to-br from-purple-600 via-pink-600 to-orange-500",
    hoverClass: "hover:from-purple-500 hover:via-pink-500 hover:to-orange-400",
    description: "Visual stories & reels",
    icon: "IG",
  },
  {
    name: "Twitter / X",
    handle: "@SmartWorldOrd",
    url: "https://twitter.com/SmartWorldOrd",
    color: "#000000",
    bgClass: "bg-slate-900",
    hoverClass: "hover:bg-slate-800",
    description: "Daily truths & threads",
    icon: "𝕏",
  },
  {
    name: "Facebook",
    handle: "SMART WORLD ORDER",
    url: "https://facebook.com/SmartWorldOrder",
    color: "#1877F2",
    bgClass: "bg-blue-700",
    hoverClass: "hover:bg-blue-600",
    description: "Community & updates",
    icon: "FB",
  },
  {
    name: "TikTok",
    handle: "@smartworldorder",
    url: "https://tiktok.com/@smartworldorder",
    color: "#010101",
    bgClass: "bg-slate-950 border border-cyan-400/40",
    hoverClass: "hover:bg-slate-900",
    description: "60-sec reality reveals",
    icon: "TK",
  },
  {
    name: "Telegram",
    handle: "t.me/smartworldorder",
    url: "https://t.me/smartworldorder",
    color: "#26A5E4",
    bgClass: "bg-sky-600",
    hoverClass: "hover:bg-sky-500",
    description: "Exclusive updates & alerts",
    icon: "TG",
  },
  {
    name: "LinkedIn",
    handle: "smartworldorder",
    url: "https://linkedin.com/company/smartworldorder",
    color: "#0A66C2",
    bgClass: "bg-blue-800",
    hoverClass: "hover:bg-blue-700",
    description: "Professional network",
    icon: "LI",
  },
  {
    name: "GitHub",
    handle: "smartworldorder",
    url: "https://github.com/smartworldorder",
    color: "#333",
    bgClass: "bg-gray-800",
    hoverClass: "hover:bg-gray-700",
    description: "Open-source projects",
    icon: "GH",
  },
];

export const MANIFESTO_POINTS = [
  {
    icon: "👁️",
    title: "Truth Through the Lens",
    text: "We expose what mainstream media hides. Every fact verified, every reality unfiltered.",
  },
  {
    icon: "⚔️",
    title: "Against Injustice",
    text: "Zero tolerance for double standards. We call out aggression, oppression, suppression, and occupation.",
  },
  {
    icon: "🌍",
    title: "Global Family",
    text: "Not a village. Not a community. A Family — bound by humanity, not borders.",
  },
  {
    icon: "🔍",
    title: "Deeper Insights",
    text: "Beyond headlines. We analyze, investigate, and bring you the layers beneath the surface.",
  },
  {
    icon: "🤝",
    title: "Unity & Integrity",
    text: "Building bridges across nations, cultures, and faiths. One world, one family.",
  },
  {
    icon: "📡",
    title: "Universality",
    text: "Every language, every nation, every voice matters. No censorship, no filters, no compromise.",
  },
];

export const TICKER_ITEMS = [
  "🌍 SMART WORLD ORDER — A Global Family Platform",
  "👁️ Both eyes on what's really going on",
  "📰 Realities and Facts at your doorstep",
  "✊ A fight against Injustice and Double Standards",
  "🔍 We bring what they hide...!",
  "🌐 Subscribe to UniOrbi on YouTube",
  "⚡ UniEdge — Connect Beyond Boundaries — Coming Soon",
  "🤝 Unity · Integrity · Universality",
  "🔔 Follow us on Instagram @smartworldorder",
  "In-sha-Allah Azza-wa-Jall",
];
